### PR TITLE
Proposing 'reply' feature

### PR DESCRIPTION
**Pull request by potch**
If you click on a message, it copies it into your canvas. You can then 'reply' to it, or collaborate!
No idea if this is something you'd want.

Submitted via the Edit Button, no idea if there's an error lol

### CODE REVIEW

**Comment by miketaylr** [comment]
:cool:

**Comment by jennschiffer** [comment]
can't replicate

**Comment by jennschiffer** [comment]
WONTFIX

**Comment by fivetanley** [comment]
can i install this with node

**Pull request closed without merging**
